"use client";

import { useMemo, useRef, useState } from "react";
import { PGN_PRESETS } from "@/data/presets";
import { createAudioEngine, generateNotesFromPgn } from "@/lib/music";

export default function ChessMusicPlayer() {
  const [sel, setSel] = useState<string>(PGN_PRESETS[0].id);
  const [tempo, setTempo] = useState<number>(120);
  const [customPgn, setCustomPgn] = useState<string>("");
  const engineRef = useRef<ReturnType<typeof createAudioEngine> | null>(null);

  const activePgn = useMemo(() => {
    const preset = PGN_PRESETS.find((p) => p.id === sel);
    return (customPgn && customPgn.trim().length > 0 ? customPgn : preset?.pgn) || "";
  }, [sel, customPgn]);

  function ensureEngine() {
    if (!engineRef.current) engineRef.current = createAudioEngine();
    return engineRef.current;
  }

  function onPlay() {
    const engine = ensureEngine();
    const events = generateNotesFromPgn(activePgn);
    if (events.length === 0) return;
    engine.play(events, tempo);
  }

  function onStop() {
    engineRef.current?.stop();
    engineRef.current = null;
  }

  return (
    <div className="player">
      <div className="controls">
        <label className="label">Preset</label>
        <select value={sel} onChange={(e) => setSel(e.target.value)} className="select">
          {PGN_PRESETS.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>

        <label className="label">Tempo: {tempo} BPM</label>
        <input
          type="range"
          min={60}
          max={180}
          step={1}
          value={tempo}
          onChange={(e) => setTempo(parseInt(e.target.value, 10))}
        />

        <div className="buttons">
          <button onClick={onPlay} className="btn primary">Play</button>
          <button onClick={onStop} className="btn">Stop</button>
        </div>
      </div>

      <div className="editor">
        <label className="label">Paste PGN (optional)</label>
        <textarea
          placeholder="Paste a PGN game here or use a preset above"
          value={customPgn}
          onChange={(e) => setCustomPgn(e.target.value)}
        />
        <p className="hint">Music is generated by mapping chess move destinations to a musical scale. Castling becomes chords.</p>
      </div>

      <style jsx>{`
        .player {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 24px;
          width: 100%;
        }
        @media (max-width: 900px) {
          .player { grid-template-columns: 1fr; }
        }
        .controls {
          padding: 16px;
          border: 1px solid rgba(255,255,255,0.12);
          border-radius: 12px;
          background: rgba(255,255,255,0.03);
        }
        .editor {
          display: flex;
          flex-direction: column;
          gap: 8px;
          padding: 16px;
          border: 1px solid rgba(255,255,255,0.12);
          border-radius: 12px;
          background: rgba(255,255,255,0.03);
        }
        textarea {
          min-height: 200px;
          padding: 10px 12px;
          border-radius: 8px;
          border: 1px solid rgba(255,255,255,0.14);
          color: inherit;
          background: rgba(0,0,0,0.2);
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
        }
        .label { display: block; margin: 8px 0 6px; opacity: 0.8; font-size: 14px; }
        .select { width: 100%; padding: 10px; border-radius: 8px; background: rgba(0,0,0,0.2); color: inherit; border: 1px solid rgba(255,255,255,0.14); }
        input[type="range"] { width: 100%; }
        .buttons { display: flex; gap: 10px; margin-top: 12px; }
        .btn { padding: 10px 14px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.14); background: rgba(0,0,0,0.2); color: inherit; cursor: pointer; }
        .btn.primary { background: #6366f1; border-color: #6366f1; color: white; }
        .hint { opacity: 0.7; font-size: 13px; margin-top: 8px; }
      `}</style>
    </div>
  );
}
